version: '3.8'

services:

  # Auth Service
  auth-service:
    image: auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: "-Djava.security.egd=file:/dev/./urandom -Dspring.jmx.enabled=false -Dmanagement.metrics.enabled=false -Dmanagement.endpoints.enabled-by-default=false -Dmanagement.endpoint.health.enabled=true"
      # Host Database Configuration
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/authdb
      SPRING_DATASOURCE_USERNAME: nishanth
      SPRING_DATASOURCE_PASSWORD: 
      # Host Redis Configuration
      SPRING_REDIS_HOST: host.docker.internal
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: password
      # Inter-service Communication
      USER_SERVICE_URL: http://user-service:8082
      # Google OAuth Configuration
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - microservices-network

  # User Service
  user-service:
    image: user-service
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: "-Djava.security.egd=file:/dev/./urandom -Dspring.jmx.enabled=false -Dmanagement.metrics.enabled=false -Dmanagement.endpoints.enabled-by-default=false -Dmanagement.endpoint.health.enabled=true"
      # Host Database Configuration
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/userdb
      SPRING_DATASOURCE_USERNAME: nishanth
      SPRING_DATASOURCE_PASSWORD: 
      # Host Kafka Configuration
      SPRING_KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
      # Inter-service Communication
      ADDRESS_SERVICE_URL: http://address-service:8083
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - microservices-network

  # Address Service
  address-service:
    image: address-service
    container_name: address-service
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: "-Djava.security.egd=file:/dev/./urandom -Dspring.jmx.enabled=false -Dmanagement.metrics.enabled=false -Dmanagement.endpoints.enabled-by-default=false -Dmanagement.endpoint.health.enabled=true"
      # Host Database Configuration
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/addressdb
      SPRING_DATASOURCE_USERNAME: nishanth
      SPRING_DATASOURCE_PASSWORD: 
      # Host Kafka Configuration
      SPRING_KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge